version: "3.9"

services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app

    working_dir: /app
    env_file:
      - ../.env

    depends_on:
      postgres:  
        condition: service_healthy
      redis:      
        condition: service_healthy

    volumes:
      - static_volume:/staticfiles
      - media_volume:/media

    ports:
      - "8000:8000"          

    networks:
      - default
      - beam-network

  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis_data:/data
    ports:
      - "6378:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default
      - beam-network        

volumes:
  static_volume:
  media_volume:
  redis_data:

networks:
  beam-network:
    # external: true
    name: beam-network
