version: "3.9"

services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    working_dir: /app
    env_file:
      - ../.env

    depends_on:
      postgres:            
        condition: service_healthy

    volumes:
      - static_volume:/staticfiles   
      - media_volume:/media          

    expose:
      - "8000"                       

    networks:
      - default
      - beam-network                


  caddy:
    build:
      context: ./nginx              
      dockerfile: Dockerfile
    container_name: caddy
    depends_on:
      - main-app
    restart: unless-stopped

    ports:
      - "80:80"                      
  

    volumes:
      - static_volume:/staticfiles:ro
      - media_volume:/media:ro
      - caddy_data:/data             
      - caddy_config:/config

    networks:
      - default
      - beam-network

volumes:
  static_volume:
  media_volume:
  caddy_data:
  caddy_config:

networks:
  beam-network:
    external: true                   
    name: beam-network
