version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: example-db
    restart: always
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - default        # сеть, создаваемая Compose-проектом
      - beam-network   # существующая внешняя сеть

volumes:
  postgres_data:
    external: true
    name: docker_compose_postgres_data

networks:
  beam-network:
    # external: true
    name: beam-network
